Add licenses button on navbar
LeagueDataRetriever/LeagueDataRetriever.github.io pull request #3
Opened 2019-12-25 14:14 UTC by AlFasGD

2019-12-26 18:05 UTC, naoei approved these changes
would be great if you could make the same changes over on the ASP.Net version of the web

2019-12-26 18:06 UTC, naoei requested changes

2019-12-26 18:06 UTC, Altenhh commented on About.html
> +					<li class="nav-item">
fix tab space

2019-12-26 23:16 UTC, AlFasGD commented
> would be great if you could make the same changes over on the ASP.Net version of the web

No idea where that's placed, so you could try that out yourself.

2019-12-27 03:25 UTC, naoei approved these changes

2019-12-27 03:25 UTC, merged